version: '3.8'

volumes:
  redis_volume:
  db:

services:
  mongo:
    image: 'mongo:6'
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

  redis:
    image: redis:7
    volumes:
      - redis_volume:/data
    restart: always
    ports:
      - '6379:6379'

